### ISSUE TITLE
How can I read data out of the partition after found using `Disk`?

### ISSUE THREAD

**Issue by schultetwin1** [google/gpt-disk-rs#244]
Hello!

I am trying to use this crate to parse the GPT and then read out data from a specific partition in my GPT partition. The problem I'm running into is I have to move my object that implements `BlockIo` into `Disk`. Once I've found the partition I need, I would love to be able to call `BlockIO::read_blocks` on my original IO device but I am unable to because it's now owned by `Disk`.

Is there a way to read the partitions in my Disk? Or some way to get my IO device back?

**Comment by nicholasbishop** [comment]
Can you `impl BlockIo` for a `&mut` reference instead? For example, there's an [impl of `BlockIo` for `BlockIoAdapter<&mut dyn ReadWriteSeek>`](https://docs.rs/gpt_disk_io/latest/gpt_disk_io/trait.BlockIo.html#impl-BlockIo-for-BlockIoAdapter%3C%26mut+dyn+ReadWriteSeek%3E). This allows `&mut File` to be be used as the source, for example. As long as the disk exists it has exclusive access to the `File`, but once the disk is dropped you can use it again.

(I'm not opposed to implementing a way to take back the underlying storage object, but wanted to check if the above works for your use case first.)

**Comment by schultetwin1** [comment]
That works for me! Thanks for the suggestion! I'll close this out for now and also close the PR.
